name: Voter Registration Unit Test CI

on: [push, pull_request]

jobs:
    build:
        runs on: ubuntu-latest

    strategy:
        matrix:
            python-version: ["3.8", "3.8", "3.9", "3.10", "3.11"]

    steps:
        - name: Checkout Repository
        uses: actions/checkout@v3
        
        - name: Set Up Python
        uses: actions/setup-python@v4
        with:
            python-version: ${{matrix.python-version}}

        - name: Install Dependencies
        run: |
            python -m install --upgrade pip
            pip install -m requirements.txt
        

        - name: Run Code Linting (Flake8)
        run: flake8 . --max-line-length = 88
        - name: Run Unit Test and Coverage Report
        run: pylint --cov = app


